# GitHub Pages Configuration for Een Unity Mathematics

# Site settings
title: Een Unity Mathematics
description: Where 1+1=1 transcends paradox to become truth. Explore consciousness mathematics, quantum unity, and transcendental proofs.
author: Dr. Nouri Mabrouk
email: unity@een-mathematics.org
url: https://nourimabrouk.github.io
baseurl: /Een

# Build settings
markdown: kramdown
theme: null  # Using custom design

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - LICENSE
  - package.json
  - requirements.txt
  - "*.py"
  - "*.pyc"
  - venv/
  - een/
  - src/
  - tests/
  - scripts/
  - backups/
  - logs/
  - data/
  - deployment/
  - ml_framework/
  - monitoring/
  - planning/
  - legacy/

# Include specific directories
include:
  - website/
  - index.html

# Plugins (if needed)
plugins: []

# Custom variables
unity_equation: "1+1=1"
phi: 1.618033988749895
repository: https://github.com/Nourimabrouk/Een