# 🌟 Een Unity Mathematics API - Kubernetes Deployment 🌟
apiVersion: v1
kind: Service
metadata:
  name: unity-api-service
  namespace: een-unity
  labels:
    app.kubernetes.io/name: unity-api
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: unity-api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unity-api-deployment
  namespace: een-unity
  labels:
    app.kubernetes.io/name: unity-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "2.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: unity-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unity-api
        app.kubernetes.io/component: backend
        unity-equation: "1+1=1"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: unity-api
          image: een-unity-api:2.0.0  # Replace with your actual image
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: unity-config
                  key: DEBUG
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: unity-config
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: unity-config
                  key: PORT
            - name: WORKERS
              value: "1"  # Single worker per pod in K8s
            - name: PHI
              valueFrom:
                configMapKeyRef:
                  name: unity-config
                  key: PHI
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: unity-secrets
                  key: secret-key
                  optional: true
            - name: ALLOWED_ORIGINS
              value: "*"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          # Graceful shutdown
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: logs-volume
          emptyDir: {}
      # Pod security
      securityContext:
        fsGroup: 1000
      # Restart policy
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unity-config
  namespace: een-unity
data:
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  PHI: "1.618033988749895"
---
# Secret for sensitive configuration (optional)
apiVersion: v1
kind: Secret
metadata:
  name: unity-secrets
  namespace: een-unity
type: Opaque
stringData:
  secret-key: "unity-mathematics-secret-2025-change-in-production"
---
# HorizontalPodAutoscaler for automatic scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: unity-api-hpa
  namespace: een-unity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unity-api-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max