# GitHub Pages Configuration for Een Unity Mathematics

# Site settings
title: Een Unity Mathematics
description: Exploring the mathematical foundation where 1+1=1 through rigorous investigation of idempotent semirings, consciousness mathematics, and philosophical implications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nouri.github.io/Een" # the base hostname & protocol

# Build settings
theme: null # We're using custom HTML/CSS
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - venv/
  - "*.py"
  - requirements.txt
  - README.md
  - LICENSE

# Include specific files
include:
  - index.html
  - proofs.html
  - css/
  - js/
  - documentation/
  - assets/

# GitHub Pages settings
github:
  repository_url: https://github.com/Nouri/Een
  repository_name: Een

# SEO settings
author: Een Unity Mathematics Project
social:
  name: Een Unity Mathematics
  links:
    - https://github.com/Nouri/Een

# Google Analytics (optional - add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X