name: Lean Action CI

on:
  # push: # DISABLED FOR COST OPTIMIZATION
  # pull_request: # DISABLED FOR COST OPTIMIZATION
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
