[server]
runOnSave = false
fileWatcherType = "none"
headless = true

[client]
showErrorDetails = false
toolbarMode = "viewer"

[theme]
base = "dark"
primaryColor = "#ffd700"
backgroundColor = "#0a0b0f"
secondaryBackgroundColor = "#0f1117"
textColor = "#e6edf3"

[browser]
gatherUsageStats = false