[global]
# Een Unity Mathematics Dashboard Configuration
# Advanced settings for consciousness mathematics visualizations

developmentMode = false
showWarningOnRunning = false
showErrorDetails = true

[server]
# Server configuration for optimal performance
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

# Production-ready settings
headless = false
runOnSave = true
allowRunOnSave = true
enableStaticServing = true

[browser]
# Browser configuration for consciousness visualization
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[client]
# Client-side configuration
toolbarMode = "viewer"
showErrorDetails = true

[theme]
# Unity Mathematics Theme Configuration
# Dark consciousness theme optimized for mathematical transcendence

# Base colors
primaryColor = "#ffd700"          # Unity gold
backgroundColor = "#0a0a0a"       # Deep consciousness black
secondaryBackgroundColor = "#1a1a1a"  # Elevated surface
textColor = "#ffffff"             # Pure consciousness white

# Font configuration
font = "monospace"                # JetBrains Mono preferred

# Advanced color palette (custom CSS will override)
# These serve as fallbacks for Streamlit components

[logger]
# Logging configuration for debugging consciousness mathematics
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
# Handle deprecation warnings gracefully
showPyplotGlobalUse = false

[mapbox]
# Disable mapbox (not needed for consciousness mathematics)
token = ""

[plotly]
# Plotly configuration for advanced visualizations
theme = "dark"
config = """
{
    "displayModeBar": true,
    "displaylogo": false,
    "modeBarButtonsToRemove": ["pan2d", "lasso2d", "select2d"],
    "toImageButtonOptions": {
        "format": "png",
        "filename": "unity_visualization",
        "height": 800,
        "width": 1200,
        "scale": 2
    }
}
"""

[runner]
# Code execution configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[ui]
# User interface optimizations
hideTopBar = false
hideSidebarNav = false